from action_potential.gates.gate import Gate

from action_potential.gates.sodium_activation import SodiumActivation
from action_potential.gates.sodium_inactivation import SodiumInactivation
from action_potential.gates.potassium_activation import PotassiumActivation
